name: CI Workflow

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches-ignore: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Fixed: Use supported Go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check formatting with gofmt
        run: |
          echo "Checking code formatting with gofmt..."
          unformatted=$(gofmt -l server)
          if [ -n "$unformatted" ]; then
            echo "Unformatted files:\n$unformatted"
            exit 1
          fi

      # Remove manual installation and use action's built-in installation
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          config: .golangci.yml
          working-directory: server
          version: v1.62.2  # Match version from your config
          args: --timeout=5m

      - name: Run go vet
        run: |
          cd server
          go vet ./...

      - name: Run tests
        run: |
          cd server
          go test ./... -v